/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Deliberth
 */
public class MDI_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form MDI_Inicio
     */
    public MDI_Inicio() {
        initComponents();
        this.setExtendedState(MDI_Inicio.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reserva de Habitaciones - Hotel Aloa Sol");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lbl_id_persona = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apaterno = new javax.swing.JLabel();
        lbl_amaterno = new javax.swing.JLabel();
        lbl_acceso = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnu_sisreserva = new javax.swing.JMenu();
        mnu_Archivo = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        mnu_Reserva = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mnu_Consulta = new javax.swing.JMenu();
        mnu_Configuracion = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnu_Herramientas = new javax.swing.JMenu();
        mnu_Ayuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnu_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 255, 255));

        lbl_id_persona.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_id_persona.setText("jLabel1");
        escritorio.add(lbl_id_persona);
        lbl_id_persona.setBounds(10, 40, 160, 15);

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombre.setText("jLabel2");
        escritorio.add(lbl_nombre);
        lbl_nombre.setBounds(150, 40, 160, 15);

        lbl_apaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_apaterno.setText("jLabel3");
        escritorio.add(lbl_apaterno);
        lbl_apaterno.setBounds(300, 40, 160, 15);

        lbl_amaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_amaterno.setText("jLabel4");
        escritorio.add(lbl_amaterno);
        lbl_amaterno.setBounds(430, 40, 160, 15);

        lbl_acceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_acceso.setText("jLabel5");
        escritorio.add(lbl_acceso);
        lbl_acceso.setBounds(600, 40, 160, 15);

        mnu_sisreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492510730_home.png"))); // NOI18N
        mnu_sisreserva.setMnemonic('f');
        mnu_sisreserva.setText("Sisreserva");
        menuBar.add(mnu_sisreserva);

        mnu_Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492511718_folder.png"))); // NOI18N
        mnu_Archivo.setMnemonic('e');
        mnu_Archivo.setText("Archivo");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492881853_aiga_baggage_lockers.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Habitaciones");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        mnu_Archivo.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/productos.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Producto");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        mnu_Archivo.add(copyMenuItem);

        menuBar.add(mnu_Archivo);

        mnu_Reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492511273_compose.png"))); // NOI18N
        mnu_Reserva.setMnemonic('h');
        mnu_Reserva.setText("Resevas");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/reservas-consumos.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Reservas y Consumos");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnu_Reserva.add(contentMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/clientes.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Clientes");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        mnu_Reserva.add(aboutMenuItem);

        menuBar.add(mnu_Reserva);

        mnu_Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492511837_19.png"))); // NOI18N
        mnu_Consulta.setText("Consultas");
        menuBar.add(mnu_Consulta);

        mnu_Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492511881_48.png"))); // NOI18N
        mnu_Configuracion.setText("Configuraciones");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/trabajadores.png"))); // NOI18N
        jMenuItem2.setText("Usuarios y Accesos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnu_Configuracion.add(jMenuItem2);

        menuBar.add(mnu_Configuracion);

        mnu_Herramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492512118_website-builder-px-png.png"))); // NOI18N
        mnu_Herramientas.setText("Herramientas");
        menuBar.add(mnu_Herramientas);

        mnu_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492511285_forum.png"))); // NOI18N
        mnu_Ayuda.setText("Ayuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Acerca de..");
        mnu_Ayuda.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ayuda");
        mnu_Ayuda.add(jMenuItem4);

        menuBar.add(mnu_Ayuda);

        mnu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/1492512407_86.png"))); // NOI18N
        mnu_Salir.setText("Salir");
        mnu_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_SalirMouseClicked(evt);
            }
        });
        menuBar.add(mnu_Salir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        JFr_Habitacion form = new JFr_Habitacion();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        JFr_Producto form = new JFr_Producto();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JFr_Cliente form = new JFr_Cliente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFr_Trabajador form = new JFr_Trabajador();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnu_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_SalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnu_SalirMouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
       JFr_Reserva form = new JFr_Reserva();
       escritorio.add(form);
       form.toFront();
       form.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFr_Login_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JLabel lbl_acceso;
    public static javax.swing.JLabel lbl_amaterno;
    public static javax.swing.JLabel lbl_apaterno;
    public static javax.swing.JLabel lbl_id_persona;
    public static javax.swing.JLabel lbl_nombre;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mnu_Archivo;
    private javax.swing.JMenu mnu_Ayuda;
    public static javax.swing.JMenu mnu_Configuracion;
    private javax.swing.JMenu mnu_Consulta;
    private javax.swing.JMenu mnu_Herramientas;
    private javax.swing.JMenu mnu_Reserva;
    private javax.swing.JMenu mnu_Salir;
    private javax.swing.JMenu mnu_sisreserva;
    // End of variables declaration//GEN-END:variables

}
